//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattingDetail
    {
        public int Id { get; set; }
        public int MatchNumber { get; set; }
        public int PlayerId { get; set; }
        public int CountryId { get; set; }
        public int Innings { get; set; }
        public int Opponents { get; set; }
        public string Dismissal { get; set; }
        public int Score { get; set; }
        public int Position { get; set; }
        public int NotOut { get; set; }
        public int Balls { get; set; }
        public int Minutes { get; set; }
        public int Fours { get; set; }
        public int Sixes { get; set; }
        public byte Hundred { get; set; }
        public byte Fifty { get; set; }
        public byte Captain { get; set; }
        public byte WicketKeeper { get; set; }
        public short HowOut { get; set; }
        public int Bowler { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Player Player { get; set; }
        public virtual Country Opponent { get; set; }
        public virtual Match Match { get; set; }
    }
}
