//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloseOfPlay
    {
        public int Id { get; set; }
        public int MatchNumber { get; set; }
        public int DayNumber { get; set; }
        public string Notes { get; set; }
    
        public virtual Match Match { get; set; }
    }
}
