//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.BattingDetails = new HashSet<BattingDetail>();
            this.BowlingDetails = new HashSet<BowlingDetail>();
            this.Matches = new HashSet<Match>();
            this.Matches1 = new HashSet<Match>();
            this.Matches2 = new HashSet<Match>();
            this.Matches3 = new HashSet<Match>();
            this.Players = new HashSet<Player>();
            this.BattingDetails1 = new HashSet<BattingDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
    
        public virtual ICollection<BattingDetail> BattingDetails { get; set; }
        public virtual ICollection<BowlingDetail> BowlingDetails { get; set; }
        public virtual ICollection<Match> Matches { get; set; }
        public virtual ICollection<Match> Matches1 { get; set; }
        public virtual ICollection<Match> Matches2 { get; set; }
        public virtual ICollection<Match> Matches3 { get; set; }
        public virtual ICollection<Player> Players { get; set; }
        public virtual ICollection<BattingDetail> BattingDetails1 { get; set; }
    }
}
