//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CricketEntities : DbContext
    {
        public CricketEntities()
            : base("name=CricketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BattingDetail> BattingDetails { get; set; }
        public virtual DbSet<BowlingDetail> BowlingDetails { get; set; }
        public virtual DbSet<CloseOfPlay> CloseOfPlays { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<FallOfWicket> FallOfWickets { get; set; }
        public virtual DbSet<FowPlayer> FowPlayers { get; set; }
        public virtual DbSet<Innings> Innings { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<VictoryType> VictoryTypes { get; set; }
        public virtual DbSet<Ground> Grounds { get; set; }
        public virtual DbSet<RenamedPlayer> RenamedPlayers { get; set; }
    }
}
