//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FallOfWicket
    {
        public FallOfWicket()
        {
            this.FowPlayers = new HashSet<FowPlayer>();
        }
    
        public int Id { get; set; }
        public int MatchNumber { get; set; }
        public int InningsOrder { get; set; }
        public int CountryId { get; set; }
        public int Wicket { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<byte> Unbroken { get; set; }
        public Nullable<byte> Multiple { get; set; }
        public Nullable<byte> Partial { get; set; }
    
        public virtual Innings Innings { get; set; }
        public virtual Match Match { get; set; }
        public virtual ICollection<FowPlayer> FowPlayers { get; set; }
    }
}
