//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FowPlayer
    {
        public int Id { get; set; }
        public int FowId { get; set; }
        public int PlayerId { get; set; }
    
        public virtual FallOfWicket FallOfWicket { get; set; }
        public virtual Player Player { get; set; }
    }
}
