//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Innings
    {
        public Innings()
        {
            this.FallOfWickets = new HashSet<FallOfWicket>();
        }
    
        public int Id { get; set; }
        public int MatchNumber { get; set; }
        public int InningsOrder { get; set; }
        public int Team { get; set; }
        public int InningsNumber { get; set; }
        public int Total { get; set; }
        public int Wickets { get; set; }
        public byte Declared { get; set; }
        public string Overs { get; set; }
        public Nullable<int> Minutes { get; set; }
    
        public virtual ICollection<FallOfWicket> FallOfWickets { get; set; }
        public virtual Match Match { get; set; }
    }
}
