//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public Match()
        {
            this.BowlingDetails = new HashSet<BowlingDetail>();
            this.CloseOfPlays = new HashSet<CloseOfPlay>();
            this.FallOfWickets = new HashSet<FallOfWicket>();
            this.Innings = new HashSet<Innings>();
            this.BattingDetails = new HashSet<BattingDetail>();
        }
    
        public int MatchNumber { get; set; }
        public int SeriesNumber { get; set; }
        public int SeriesId { get; set; }
        public int TestNumber { get; set; }
        public int HomeTeam { get; set; }
        public int AwayTeam { get; set; }
        public string MatchDesignator { get; set; }
        public string SeriesYear { get; set; }
        public string MatchDate { get; set; }
        public string Location { get; set; }
        public int Toss { get; set; }
        public string ResultString { get; set; }
        public int WhoWon { get; set; }
        public int VictoryType { get; set; }
        public int HowMuch { get; set; }
        public int BallsPerOver { get; set; }
    
        public virtual ICollection<BowlingDetail> BowlingDetails { get; set; }
        public virtual ICollection<CloseOfPlay> CloseOfPlays { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Country Country2 { get; set; }
        public virtual Country Country3 { get; set; }
        public virtual ICollection<FallOfWicket> FallOfWickets { get; set; }
        public virtual ICollection<Innings> Innings { get; set; }
        public virtual ICollection<BattingDetail> BattingDetails { get; set; }
    }
}
