//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.BattingDetails = new HashSet<BattingDetail>();
            this.BowlingDetails = new HashSet<BowlingDetail>();
            this.FowPlayers = new HashSet<FowPlayer>();
            this.Countries = new HashSet<Country>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SortNamePart { get; set; }
        public string OtherNamePart { get; set; }
        public short Debut { get; set; }
        public Nullable<int> NameChecked { get; set; }
        public string KnownAs { get; set; }
        public string BattingType { get; set; }
        public string BowlingType { get; set; }
        public Nullable<int> RenamedId { get; set; }
    
        public virtual ICollection<BattingDetail> BattingDetails { get; set; }
        public virtual ICollection<BowlingDetail> BowlingDetails { get; set; }
        public virtual ICollection<FowPlayer> FowPlayers { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
    }
}
